# Generated by Django 4.2.9 on 2024-04-12 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("athletic_department", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="athlete", name="name",),
        migrations.RemoveField(model_name="athlete", name="scholarship_amount",),
        migrations.RemoveField(model_name="athlete", name="team",),
        migrations.RemoveField(model_name="employee", name="name",),
        migrations.RemoveField(model_name="employee", name="salary",),
        migrations.RemoveField(model_name="employee", name="team",),
        migrations.RemoveField(model_name="equipment", name="cost",),
        migrations.RemoveField(model_name="equipment", name="name",),
        migrations.RemoveField(model_name="equipment", name="team",),
        migrations.RemoveField(model_name="event", name="expense",),
        migrations.RemoveField(model_name="event", name="name",),
        migrations.RemoveField(model_name="event", name="team",),
        migrations.AddField(
            model_name="athlete",
            name="academic_level",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="athlete",
            name="athleteid",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="athlete",
            name="contact",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="athlete",
            name="firstname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="athlete",
            name="lastname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="athlete",
            name="position",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="employeeid",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="firstname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="lastname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="employee",
            name="title",
            field=models.CharField(default="Employee", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="type",
            field=models.CharField(
                choices=[("Salary", "Salary"), ("Hourly", "Hourly")],
                default="Salary",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="annual_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="equipment",
            name="equipmentid",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="teamid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="athletic_department.team",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="year",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="eventid",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="event",
            name="opponent",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="teamid",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="athletic_department.team",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="team",
            name="established_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="income",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scholarshipid", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("donor", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                (
                    "athleteid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="athletic_department.athlete",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rankid", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "teamid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="athletic_department.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incomeid", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "teamid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="athletic_department.team",
                    ),
                ),
            ],
        ),
    ]
