# Generated by Django 4.2.9 on 2024-04-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletic_department", "0002_remove_athlete_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="sport_type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
